# Increase Starship command scan & duration time-outs
scan_timeout = 80
command_timeout = 1000

# Disable the blank line at the start of the prompt
add_newline = false

format = """
╭─\
[ $os](bg:#4a4a4a fg:#FFFFFF)[](bg:#4a4a4a fg:#aca9a9)\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$kubernetes\
${custom.talosconfig}\
${custom.omniconfig}\
[ ](bg:#4a4a4a)\
[](fg:#4a4a4a)\
$fill\
[](fg:#4a4a4a)\
$status\
$cmd_duration\
$time \
$line_break\
╰─\
[ ](bold green)
"""

[fill]
symbol = "─"
style = "fg:#aca9a9"

[status]
format = "[ $symbol]($style)"
style = "bg:#4a4a4a fg:bold red"
symbol = "[$status ✘ ](bg:#4a4a4a fg:red bold)"
success_symbol = "[󰄬 ](bg:#4a4a4a fg:green bold)"
disabled = false

[character]
format = "$symbol"
success_symbol = "[ 󰄬 ](bg:#4a4a4a green bold)"
error_symbol = "[ ✘ ](bg:#4a4a4a red bold)"

[cmd_duration]
format = "[ ](bg:#4a4a4a fg:#aca9a9)[$duration  ]($style)"
min_time = 200
style = "bg:#4a4a4a fg:#ef8f0a"
show_milliseconds = false

[time]
disabled = false
style = "bg:#4a4a4a fg:#FFFFFF"
format = "[ ](bg:#4a4a4a fg:#aca9a9)[$time  ]($style)"

[directory]
style = "bg:#4a4a4a fg:#03bb51"
format = "[$path]($style)[ ](bg:#4a4a4a fg:#aca9a9)"
home_symbol = "  ~"
read_only = ""
truncation_symbol = "  ~/../"
truncation_length = 2
truncate_to_repo = false

[git_branch]
symbol = " "
format = "[ $symbol$branch]($style)"
style = "bg:#4a4a4a fg:#ef8f0a"

[git_commit]
format = '[\($hash\)]($style)'
style = 'bg:#4a4a4a fg:#ef8f0a'
commit_hash_length = 7
disabled = false
only_detached = false

[git_status]
format = '([ | $all_status$ahead_behind]($style))[](bg:#4a4a4a fg:#aca9a9)'
style = "bg:#4a4a4a fg:#ef8f0a"
conflicted = '[ confliced=${count}](bg:#4a4a4ared) '
up_to_date = '[ up-to-date](bg:#4a4a4a fg:#ef8f0a) '
untracked = '[ untracked=${count}](bg:#4a4a4a red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](bg:#4a4a4a green) '
modified = '[󰛿 modified=${count}](bg:#4a4a4a yellow) '
staged = '[󰐗 staged=${count}](bg:#4a4a4a green) '
renamed = '[󱍸 renamed=${count}](bg:#4a4a4a yellow) '
deleted = '[󰍶 deleted=${count}](bg:#4a4a4a red) '

[git_metrics]
disabled = true
format = "[$added]($added_style)[ ](bg:#4a4a4a)"
added_style = "bg:#4a4a4a fg:#ef8f0a"

[hostname]
ssh_only = false
format = ' $hostname'
trim_at = '.local'
disabled = false

[kubernetes]
disabled = false
style = "bg:#4a4a4a fg:#0ac6ef"
symbol = "[⎈ ](bg:#4a4a4a fg:#0ac6ef)"
format = '[ $symbol$context( \($namespace\))]($style)[ ](bg:#4a4a4a fg:#aca9a9)'
[[kubernetes.contexts]]
context_pattern = "onprem-omni-stage-pnap"
context_alias = " STAGE-PNAP "
style = "bg:#4a4a4a bold red"
[[kubernetes.contexts]]
context_pattern = "onprem-omni-stage"
context_alias = " STAGE "
style = "bg:#4a4a4a bold red"

[line_break]
disabled = false

[os]
#format = '[NixOS](bg:#4a4a4a bold white)'   
format = '[$symbol](bg:#4a4a4a bold white)'   
disabled = false

[os.symbols]
Windows = ' '
Ubuntu = ''
Macos = ''
Linux = '󰣛'
NixOS = ''

[custom.talosconfig]
description = "Shows the current Talos context"
command = '''talosctl config info 2>/dev/null | awk '/^Current context:/ {print $3}' '''
when = '''command -v talosctl >/dev/null 2>&1'''
symbol = " "
style = "bg:#4a4a4a fg:#c678dd"
format = '[ $symbol$output]($style)[ ](bg:#4a4a4a fg:#aca9a9)'
shell = ["bash", "--noprofile", "--norc"]

[custom.omniconfig]
description = "Shows the current Omni context"
command = '''omnictl config info 2>/dev/null | awk '/^Current context:/ {print $3}' '''
when = '''command -v omnictl >/dev/null 2>&1'''
symbol = "󰏉 "
style = "bg:#4a4a4a fg:#56b6c2"
format = '[ $symbol$output]($style)[ ](bg:#4a4a4a fg:#aca9a9)'
shell = ["bash", "--noprofile", "--norc"]
